..\..\Debug\regplate.exe photo.jpg
..\..\Debug\regplate.exe hpp.jpg
..\..\Debug\regplate.exe hwa.jpg
..\..\Debug\regplate.exe sk1.jpg
..\..\Debug\regplate.exe kos.jpg
..\..\Debug\regplate.exe dbl.jpg
..\..\Debug\regplate.exe kr.jpg
..\..\Debug\regplate.exe esi.jpg
..\..\Debug\regplate.exe wor.jpg
